# Create a null vector of size 10 but the fifth value which is 1

In [4]:
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# Create a vector with values ranging from 10 to 49.

In [7]:
import numpy as np
vector = np.arange(10,49)
print("Original vector:")
print(vector)

Original vector:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


# Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from [1,2,0,0,4,0]

In [12]:
q=np.array([1,2,0,0,4,0])
q[q>0]

array([1, 2, 4])

# Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
z=np.random.randint(1,100,(10,10))
print(z)
zmin,zmax=z.min(),z.max()
print('minimum value is:',zmin)
print('maximum value is:',zmax)

[[44 56  7 82 27  1 62 11 23 61]
 [62 14 44 79 47 85 97 84 19 18]
 [49 51  3 33 30 23  7  3 18 11]
 [35 77 37  8 83  7  1 55 88 40]
 [28 13 89 71 87 87 72 79 49 96]
 [91 75 51 83 63 58 19 22 52 11]
 [56 57 95  5 20 49 65  6 19 42]
 [72 69 48 22 21 40 90 63  4  7]
 [62 57 53 92 43 18 16 86 35 80]
 [25 13 78 74 33 57 34 81 84 77]]
minimum value is: 1
maximum value is: 97


# Create a random vector of size 30 and find the mean value.

In [32]:
import numpy as np
vector = np.random.random(30)
print("Original array:")
print(vector)
print('mean value is:',np.mean(vector))


Original array:
[0.2904222  0.66577786 0.92701723 0.81209221 0.73841195 0.3739962
 0.43675804 0.0176491  0.42713253 0.75739061 0.98887715 0.03951632
 0.04397703 0.48628593 0.46388926 0.37900773 0.93767006 0.86136057
 0.42105697 0.56263991 0.7382116  0.31836608 0.87742241 0.8950367
 0.3893806  0.473882   0.86452225 0.40635523 0.33973459 0.64009101]
mean value is: 0.5524643775464247
